let strip = neopixel.create(DigitalPin.P2, 12, NeoPixelMode.RGB)
strip.showColor(neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.forever(function () {
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(200)
    strip.clear()
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
})
